function R = rotation(ang)
R = [cos(ang(3))*cos(ang(2)),...
     cos(ang(3))*sin(ang(2))*sin(ang(1)) - sin(ang(3))*cos(ang(1)),...
     cos(ang(3))*sin(ang(2))*cos(ang(1)) + sin(ang(3))*sin(ang(1)); ...
     sin(ang(3))*cos(ang(2)) ,...
     sin(ang(3))*sin(ang(2))*sin(ang(1)) + cos(ang(3))*cos(ang(1)),...
     sin(ang(3))*sin(ang(2))*cos(ang(1)) - cos(ang(3))*sin(ang(1));...
     -sin(ang(2)), cos(ang(2))*sin(ang(1)), cos(ang(2))*cos(ang(1))];

end